on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm (official action)
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Ensure pnpm available (fallback to corepack/npm if needed)
        run: |
          echo "PATH before check: $PATH"
          if ! command -v pnpm >/dev/null 2>&1; then
            echo "pnpm not found via action, trying corepack..."
            corepack enable || true
            corepack prepare pnpm@8.8.0 --activate || true
          fi
          if ! command -v pnpm >/dev/null 2>&1; then
            echo "pnpm still not found, installing globally as last resort..."
            npm i -g pnpm@8 || true
          fi
          echo "pnpm version and node version:"
          pnpm -v || true
          node -v || true

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
