on:
  push:
    branches:
      - deploy

permissions:
  contents: read
  actions: read

jobs:
  build-and-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm (official action)
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Verify pnpm and node (debug)
        run: |
          echo "PATH: $PATH"
          pnpm -v
          node -v

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build site
        run: pnpm run build

      - name: Run pnpm audit (report)
        run: pnpm audit --json > audit.json || true

      - name: Upload build artifact (preview)
        uses: actions/upload-artifact@v4
        with:
          name: preview-dist
          path: ./dist
